### ISSUE TITLE
Which style of computed property to use

### ISSUE THREAD

**Issue by HeroicEric** [envoy/styleguides#27]
In my research I have not found a good reason for us to use the second example below:

```
fullName: computed('firstName', 'lastName', function() {
  return [this.firstName, this.lastName].join(' ');
})

// vs.

fullName: computed('firstName', 'lastName', {
  get() {
    return [this.firstName, this.lastName].join(' ');
  }
})
```

- It does not match what most new devs will learn from [the guides](https://guides.emberjs.com/release/object-model/computed-properties/). There is one example that includes this but it is only used in the case where you actually want to define a `set()`, which is not common
- It requires at least 2 extra lines per computed property
- It forces your actual code to be indented one level deeper

Either choice, I think it is better to only have one way that we do this so we don't confuse people trying to learn our codebase

**Comment by thomascchen** [comment]
I think the first example makes sense. As a person new to the codebase, I can confirm I was confused when I saw the second example. I think that probably makes the most sense to use only if it's really needed, i.e. if we're defining `set()` which probably isn't that often.

**Comment by HeroicEric** [comment]
In Slack @steveszc said:

> I don't really have a preference. I've always done `function` syntax since that's what the guides seem to teach, but I think `get` syntax is easier to understand/reason about if you aren't as familiar with ember (makes it clear this thing is a getter). I'm fine with either as long as we can be consistent about it. Is either format work better for decorator syntax?

**Comment by HeroicEric** [comment]
@steveszc I kind of agree with that point about devs coming from outside Ember but I'm also not sure if that is true. The getter being inside of the computed seems like it would already throw someone who is not familiar off enough that they would go look up the docs and then maybe have a hard time finding an example.

We should get some input from someone who recently went through this :)

**Comment by ryanlabouve** [comment]
Does this change at all with the decorators stuff?

**Comment by HeroicEric** [comment]
@ryanlabouve yet with decorators it will just be

```js
@computed('firstName', 'lastName')
get fullName() {
  return [this.firstName, this.lastName].join(' ');
}
```

**Comment by cafreeman** [comment]
We should absolutely ditch the `get` syntax. It's only useful for when you need to also define a setter, which we don't ever do (thankfully). Plus, in decorator/es6 class land, setters would be defined with an actual JS setter anyway.

**Comment by ryanlabouve** [comment]
I vote for 

```
fullName: computed('firstName', 'lastName', function() {
  return [this.firstName, this.lastName].join(' ');
})
```

**Comment by jennz0r** [comment]
n00b ember user here. i've definitely found the use of `get()` in a computed property odd and confusing syntax. would love to change it to the former of the two listed in the PR description.
